# Introduction

## Dataset
Generate random age

In [1]:
num = [28, 30, 31, 33, 19, 26, 25, 26, 37, 22, 37, 24, 21, 32, 31, 33, 34,
       40, 38, 32, 36, 32, 23, 20, 30, 42, 20, 37, 21, 27, 25, 40, 24, 39,
       25, 23, 32, 25, 21, 41, 34, 40, 31, 33, 32, 31, 18, 18, 42, 29]

# Numpy


## Import numpy
Import libraries and write settings here.

## Creating a numpy array

array([28, 30, 31, 33, 19, 26, 25, 26, 37, 22, 37, 24, 21, 32, 31, 33, 34,
       40, 38, 32, 36, 32, 23, 20, 30, 42, 20, 37, 21, 27, 25, 40, 24, 39,
       25, 23, 32, 25, 21, 41, 34, 40, 31, 33, 32, 31, 18, 18, 42, 29])

## Dimension
`ndim` output the number of dimensions of an array 

In [4]:
example = np.array([[1,2,3],
                   [3,4,5],
                   [6,7,8]])

2

1

## Shape and Size
output the size of the dimension

In [7]:
example.shape

(3, 3)

In [8]:
age.shape

(50,)

In [9]:
example.size

9

In [1]:
age.size

NameError: name 'age' is not defined

## Mathematical operations

array([30, 32, 33, 35, 21, 28, 27, 28, 39, 24, 39, 26, 23, 34, 33, 35, 36,
       42, 40, 34, 38, 34, 25, 22, 32, 44, 22, 39, 23, 29, 27, 42, 26, 41,
       27, 25, 34, 27, 23, 43, 36, 42, 33, 35, 34, 33, 20, 20, 44, 31])

## Trigonometric function

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

## Conditional operations

array([False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False,  True, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False])

## Indexing and slice

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

### Index a number

5

### First 10 ages

array([28, 30, 31, 33, 19, 26, 25, 26, 37, 22])

### The last row of example

array([6, 7, 8])

# Pandas

### Creating new pandas series

#### Without index

0    0.867305
1    0.642822
2    0.698573
3    0.377474
4    0.203253
dtype: float64

#### With index

a    0.914300
b    0.322954
c    0.836491
d    0.091243
e    0.733906
dtype: float64

#### Creating pandas series from a dictionary

a    1
b    2
c    3
d    4
dtype: int64

## Data frame
DataFrame is a 2D data structure with columns that can be of different datatypes. It
can be seen as a table. 

### Creating dataframe

#### From dictionary

a1 a2
0   1  a
1   2  b
2   3  c
3   4  d
4   5  e

#### From data series

a1   a2
0   1    a
1   2    b
2   3    c
3   4    d
4   5  NaN

## Import Pandas

## Get our data

To get csv use `pd.read_csv`  
To get xlsx(excel) format, use `pd.read_excel`  
To get data from database 
* `pd.read_sql_table`
* `pd.read_sql_query`

## Show data

     RANK                  PLAYER POSITION                    TEAM  \
0       1             Kobe Bryant       SF      Los Angeles Lakers   
1       2             Joe Johnson       SF           Brooklyn Nets   
2       3            LeBron James       SF     Cleveland Cavaliers   
3       4         Carmelo Anthony       SF         New York Knicks   
4       5           Dwight Howard        C         Houston Rockets   
5       6              Chris Bosh       PF              Miami Heat   
6       7              Chris Paul       PG    Los Angeles Clippers   
7       8            Kevin Durant       SF   Oklahoma City Thunder   
8       9            Derrick Rose       PG           Chicago Bulls   
9      10             Dwyane Wade       SG              Miami Heat   
10     11       LaMarcus Aldridge       PF       San Antonio Spurs   
11     12              Kevin Love       PF     Cleveland Cavaliers   
12     13              Marc Gasol        C       Memphis Grizzlies   
13     14           

## Limit amount to display

RANK           PLAYER POSITION                 TEAM  SALARY ($M)
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500
3     4  Carmelo Anthony       SF      New York Knicks    22.875000
4     5    Dwight Howard        C      Houston Rockets    22.359364

## Data type

RANK             int64
PLAYER          object
POSITION        object
TEAM            object
SALARY ($M)    float64
dtype: object

## The columns

Index(['RANK', 'PLAYER', 'POSITION', 'TEAM', 'SALARY ($M)'], dtype='object')

## Selecting a single column

### Square bracket

0        Kobe Bryant
1        Joe Johnson
2       LeBron James
3    Carmelo Anthony
4      Dwight Howard
Name: PLAYER, dtype: object

### Dot

0        Kobe Bryant
1        Joe Johnson
2       LeBron James
3    Carmelo Anthony
4      Dwight Howard
Name: PLAYER, dtype: object

## Selecting multiply roles

RANK           PLAYER  SALARY ($M)
0     1      Kobe Bryant    25.000000
1     2      Joe Johnson    24.894863
2     3     LeBron James    22.970500
3     4  Carmelo Anthony    22.875000
4     5    Dwight Howard    22.359364
5     6       Chris Bosh    22.192730
6     7       Chris Paul    21.468695
7     8     Kevin Durant    20.158622
8     9     Derrick Rose    20.093064
9    10      Dwyane Wade    20.000000

## Selecting Rows

RANK                    10
PLAYER         Dwyane Wade
POSITION                SG
TEAM            Miami Heat
SALARY ($M)             20
Name: 9, dtype: object

## Create a new column

RANK           PLAYER POSITION                 TEAM  SALARY ($M)  \
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000   
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863   
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500   
3     4  Carmelo Anthony       SF      New York Knicks    22.875000   
4     5    Dwight Howard        C      Houston Rockets    22.359364   

   SOME STUFF  
0          20  
1          20  
2          20  
3          20  
4          20

## Remove columns

RANK           PLAYER POSITION                 TEAM  SALARY ($M)
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500
3     4  Carmelo Anthony       SF      New York Knicks    22.875000
4     5    Dwight Howard        C      Houston Rockets    22.359364

## Engineering age

### Shape of the data

(417, 5)

### Generate random values

array([42, 26, 27, 39, 21, 29, 34, 21, 41, 44])

(417,)

array([32, 35, 21, 47, 19, 38, 22, 42, 45, 31])

(417,)

RANK           PLAYER POSITION                 TEAM  SALARY ($M)  AGE
0     1      Kobe Bryant       SF   Los Angeles Lakers    25.000000   32
1     2      Joe Johnson       SF        Brooklyn Nets    24.894863   35
2     3     LeBron James       SF  Cleveland Cavaliers    22.970500   21
3     4  Carmelo Anthony       SF      New York Knicks    22.875000   47
4     5    Dwight Howard        C      Houston Rockets    22.359364   19

## Create new row

#### Create new dataframe

#### Convert to dataframe

RANK         PLAYER TEAM  SALARY ($M)
0   418  Solomon Igori  PDC         30.0

AGE                  PLAYER POSITION  RANK  SALARY ($M)  \
0     NaN           Solomon Igori      NaN   418    30.000000   
1    32.0             Kobe Bryant       SF     1    25.000000   
2    35.0             Joe Johnson       SF     2    24.894863   
3    21.0            LeBron James       SF     3    22.970500   
4    47.0         Carmelo Anthony       SF     4    22.875000   
5    19.0           Dwight Howard        C     5    22.359364   
6    38.0              Chris Bosh       PF     6    22.192730   
7    22.0              Chris Paul       PG     7    21.468695   
8    42.0            Kevin Durant       SF     8    20.158622   
9    45.0            Derrick Rose       PG     9    20.093064   
10   31.0             Dwyane Wade       SG    10    20.000000   
11   21.0       LaMarcus Aldridge       PF    11    19.689000   
12   23.0              Kevin Love       PF    12    19.689000   
13   23.0              Marc Gasol        C    13    19.688000   
14   36.0           Blake Griffin       PF    14    18.907726   
15   19.0            Paul Millsap       PF    15    18.671659   
16   37.0             Paul George       SF    16    17.120106   
17   30.0       Russell Westbrook       PG    17    16.744218   
18   21.0            Kyrie Irving       PG    18    16.407501   
19   45.0           Kawhi Leonard       SF    19    16.407500   
20   38.0             Enes Kanter        C    20    16.407500   
21   49.0            Jimmy Butler       SG    21    16.407500   
22   29.0           Tobias Harris       SF    22    16.000000   
23   25.0               John Wall       PG    23    15.851950   
24   34.0        DeMarcus Cousins        C    24    15.851950   
25   31.0            James Harden       SG    25    15.756438   
26   42.0             Roy Hibbert        C    26    15.592217   
27   20.0             Eric Gordon       SG    27    15.514031   
28   42.0           Klay Thompson       SG    28    15.501000   
29   35.0               David Lee       PF    29    15.493680   
..    ...                     ...      ...   ...          ...   
388  48.0            Jarell Eddie       SG   388     0.561716   
389  20.0        Greg Whittington       SF   389     0.525093   
390  34.0         Josh Richardson       SG   390     0.525093   
391  47.0           Corey Hawkins       PG   391     0.525093   
392  19.0          Aaron Harrison       SG   392     0.525093   
393  38.0           Shannon Scott       PG   393     0.525093   
394  18.0      Ronald Roberts Jr.       PF   394     0.525093   
395  28.0          Treveon Graham       SG   395     0.525093   
396  23.0           Jarrid Famous       PF   396     0.525093   
397  30.0            Luis Montero       SG   397     0.525093   
398  22.0         Cliff Alexander       PF   398     0.525093   
399  30.0             Bo McCalebb       PG   399     0.525093   
400  25.0         Lamar Patterson       SG   400     0.525093   
401  24.0         Terran Petteway       SG   401     0.525093   
402  24.0             Steve Novak       SF   402     0.289755   
403  47.0        Anderson Varejao       PF   403     0.289755   
404  36.0          JaKarr Sampson       SG   404     0.258489   
405  30.0      Bryce Dejean-Jones       SG   405     0.169883   
406  18.0           Lorenzo Brown       PG   406     0.111444   
407  29.0            Ryan Hollins        C   407     0.111444   
408  35.0              Jeff Ayres       PF   408     0.111444   
409  39.0             Erick Green       PG   409     0.099418   
410  42.0         Sean Kilpatrick       SG   410     0.099418   
411  19.0           Keith Appling       PG   411     0.061776   
412  43.0         Orlando Johnson       SG   412     0.055722   
413  40.0         Elliot Williams       SG   413     0.055722   
414  34.0            Phil Pressey       PG   414     0.055722   
415  27.0            Jordan McRae       SG   415     0.049709   
416  33.0          Cory Jefferson       PF   416     0.049709   
417  24.0  Thanasis Antetokounmpo       S

## Delete row

# Conclusion